### ISSUE TITLE
NOVAS_URL?

### ISSUE THREAD

**Issue by zvezdochiot** [brhamon/astro#1]
https://github.com/brhamon/astro/blob/17fde7580fdb5641c1c52de71500a0d622e69224/Makefile#L4

❓ Maybe?:  
https://github.com/indigo-astronomy/novas

**Comment by brhamon** [comment]
Thank you for an excellent suggestion.

All the NOVAS links disappeared some time back. I had been reluctant to switch to a repository not controlled by the original copyright holder, but this one's been posted for more than four years; so perhaps they're willing to allow it to be licensed with fewer restrictions.

I'll push something to address this shortly.

**Comment by brhamon** [comment]
Sorry for the delay. The Naval Observatory updated their web site, and all the URLs changed. Also the IERS moved their downloads (no more FTP!). I've push a commit to fix things. Please let me know if you have any trouble.
